/// Every prompt the app can offer, grouped by theme.
///
/// The themes only organise the file; the deck draws from all of them at once,
/// and the theme's name is shown under each prompt as a quiet label.
///
/// The first five themes come from Buddhist and mindfulness practice -- the Four
/// Foundations of Mindfulness, the Five Remembrances, the four heart practices,
/// the second arrow, Zen koans; Thich Nhat Hanh, Pema Chödrön, Shunryu Suzuki,
/// Sharon Salzberg, Ajahn Chah. The rest draw on The Artist's Way, Byron Katie,
/// IFS, ACT values work, Naikan, the Stoic evening review, the Ignatian examen,
/// fear-setting and Four Thousand Weeks.
///
/// All of them are in one voice: lowercase, one question, no jargon. A prompt
/// should open something up, never assign homework.
///
/// Adding or removing a prompt changes the count, which reshuffles everyone's
/// deck on the next launch. That is deliberate -- see `PromptDeck`.
enum PromptLibrary {
    static let themes: [PromptTheme] = [
        PromptTheme(name: "this moment", prompts: [
            "what is actually happening right now, before the story about it?",
            "can you feel one whole breath, from its beginning to its end?",
            "is this moment pleasant, unpleasant, or neither — and how can you tell?",
            "what is your mind doing right now: planning, remembering, or here?",
            "where is the stillness in this room?",
            "what would it be like to drink your tea as if it were the whole morning?",
            "what are your feet touching, and how do they know?",
            "what is the quietest sound you can hear?",
            "which thought keeps arriving, and can you watch it come and go without following it?",
            "what are you waiting for this moment to become?",
            "if you stopped trying to get anywhere for one minute, what would be left?",
            "what does being here feel like, compared with thinking about being here?",
            "what is the mood of your mind this morning, if you describe it like weather?",
            "can you notice the space between two thoughts?",
            "what did your mind reach for first when you woke up?",
            "which part of this moment are you pushing away?",
            "which part of this moment are you trying to hold on to?",
            "what would you notice if you did the next thing half as fast?",
            "what is already complete about this moment, without anything added?",
            "where does your attention rest when you let it rest?",
            "what is the breath doing while you’re busy with everything else?",
            "what is one ordinary thing you could do today with your full presence?",
            "when you listen for silence, what do you hear first?",
            "what would change if you treated this morning as the only one?",
            "what is here right now that doesn’t need fixing?",
        ]),
        PromptTheme(name: "impermanence", prompts: [
            "what in your life is changing so slowly you haven’t noticed?",
            "what are you treating as permanent that is already passing?",
            "what feeling from last week has already gone, without your help?",
            "if this difficult season is temporary, how would you want to move through it?",
            "if this sweet season is temporary, how would you want to savour it?",
            "what would you say to someone you love if you remembered you won’t always have them?",
            "what will you have to let go of eventually, and how could you practise loosening now?",
            "which version of yourself are you still trying to keep alive?",
            "what do you own that owns you a little?",
            "what did you once think you couldn’t live without?",
            "what would you do differently today if you truly knew it wouldn’t come again?",
            "which worry from a year ago no longer exists?",
            "what is being born in your life right now, however small?",
            "what is ending in your life, and have you let it end?",
            "what are you gripping as though holding it tighter could keep it?",
            "what would it mean to be at peace with not knowing how much time you have?",
            "what would you want to be doing when your life is finally unhurried?",
            "what are you postponing as though there were always more time?",
            "which of your certainties has already quietly changed?",
            "what would it mean to love something without needing it to stay?",
            "what will matter to you on your last ordinary morning?",
            "what has aged beautifully in your life?",
            "what is the kindest way to hold something you know you’ll lose?",
            "what does the changing light of this season ask of you?",
            "since everything you own will scatter, what would you like to leave in people instead?",
        ]),
        PromptTheme(name: "kindness", prompts: [
            "what would you wish for yourself this morning, if you wished it the way you’d wish it for a child?",
            "who is struggling right now whom you could simply hold in mind for a moment?",
            "what would it feel like to meet your own mistakes the way a good friend would?",
            "whose happiness could you be glad about today, without comparing?",
            "what would it take to feel a little warmth toward someone who irritates you?",
            "what might the difficult person in your life be suffering from?",
            "where is the kindness in you that nobody asks for?",
            "what would you say to the part of you that is hurting, if you spoke gently?",
            "who has been quietly kind to you, and what did it feel like to receive it?",
            "what would it mean to wish someone well and ask for nothing back?",
            "how do you speak to yourself when no one else is listening?",
            "what small good could you do today that nobody would ever trace to you?",
            "what would equanimity look like in the situation you’re most worried about?",
            "whose success stings a little, and what would happiness for them feel like?",
            "what does your heart feel like when you remember that everyone wants to be happy?",
            "when did someone’s patience with you change something?",
            "what would you forgive yourself for, if forgiving didn’t mean excusing?",
            "who in your life is easiest to love, and what can you learn from that ease?",
            "what kind of attention makes someone feel truly seen?",
            "what would it be like to wish yourself well without earning it first?",
            "what is the gentlest true thing you could say to someone today?",
            "where could you soften, rather than win?",
            "what might the people you pass each day, but never speak to, be carrying?",
            "what would a compassionate response to your own tiredness be?",
            "may you be well — who else, this morning, would you like to say that to?",
        ]),
        PromptTheme(name: "letting go", prompts: [
            "what are you adding to today’s pain that the pain itself didn’t ask for?",
            "which small hurt have you turned into a long story?",
            "what do you want so strongly that it has started to hurt?",
            "what are you resisting that is already here?",
            "which craving shows up most often when you’re tired?",
            "what would happen if you let yourself not know yet?",
            "what would you have to accept for your shoulders to drop?",
            "which restlessness is really a feeling you’d rather not sit with?",
            "what doubt keeps you circling instead of beginning?",
            "what are you holding on to because letting go would feel like losing?",
            "what grudge are you still carrying, and what does carrying it cost?",
            "where are praise and blame steering you more than you’d like?",
            "what would you let fall away if you trusted you’d still be yourself?",
            "which expectation of today could you set down right now?",
            "what feeling are you trying to fix that might only need to be felt?",
            "what is the difference between what happened and what you keep telling yourself happened?",
            "what would it mean to let this be as it is, just for now?",
            "which comparison is stealing your ease this week?",
            "what are you pushing so hard to control that it’s controlling you?",
            "what would you stop defending if no one were keeping score?",
            "what are you craving right now, and what does the craving feel like in the body?",
            "what would it feel like to hold your plans a little more lightly?",
            "what is one thing you could let someone else be wrong about?",
            "when you imagine putting down the heaviest thing, what do your hands want to do?",
            "what can you release today, without needing to understand it first?",
        ]),
        PromptTheme(name: "beginner's mind", prompts: [
            "what would you see this morning if you’d never seen it before?",
            "what would you find if you met yourself this morning without your usual opinions?",
            "what was your face before your parents were born?",
            "what would you ask your life if you expected an answer?",
            "what is something familiar you could approach as a stranger today?",
            "what are you expert enough at to have stopped noticing?",
            "what would a five-year-old find astonishing about your day?",
            "who is it that is reading this question?",
            "what question are you carrying that doesn’t need answering yet?",
            "what could you learn from someone you usually dismiss?",
            "what would you do today if you let yourself be a beginner at it?",
            "where does a thought go when you stop thinking it?",
            "what if the obstacle in front of you were also the path?",
            "what would you notice if you stopped labelling things for an hour?",
            "what does ‘i don’t know’ feel like when you let it be peaceful?",
            "what is looking out through your eyes right now?",
            "what do you do out of habit that you could do with curiosity instead?",
            "what would your life look like to someone seeing it for the first time?",
            "when did not knowing turn out to be a gift?",
            "what if the thing you’re surest of is only half the picture?",
            "what is hidden in plain sight in your home?",
            "what would a wise old teacher ask you about this week?",
            "what if you were exactly where you need to be to learn what you need to learn?",
            "chop wood, carry water — what are today’s wood and water?",
            "what would you discover if you sat still and let the day come to you?",
        ]),
        PromptTheme(name: "wanting", prompts: [
            "what would you still want if nobody could ever see you having it?",
            "what sounds lovely to you but not especially impressive?",
            "what do you keep trying to find a practical reason for wanting?",
            "which dream is really a wish for a feeling?",
            "what do you want that you haven’t said out loud yet?",
            "what are you quietly hoping someone will give you permission to do?",
            "which of your wants feels borrowed from someone else?",
            "what small thing have you been meaning to let yourself have?",
            "if you had five other lives, what would one of them be spent doing?",
            "which of your imaginary lives could you borrow an afternoon from this week?",
            "what are you pretending not to want so you won’t be disappointed?",
            "what would you ask for if asking cost nothing?",
            "what does a wish feel like before it turns into a plan?",
            "what do you want more of that can’t be bought?",
            "which of your goals would you drop if nobody asked how it was going?",
            "what are you hungry for that isn’t food?",
            "what would you choose if you trusted yourself to choose well?",
            "what wish have you carried so long you’ve stopped noticing it?",
            "what would you want if you weren’t already bracing for no?",
            "is the life you’re living the same one that wants to live in you?",
            "which of your plans is secretly a way to be seen?",
            "what does happiness look like for you at this exact point in your life?",
            "if you could wake up tomorrow with one new quality, which would you choose?",
            "what would a slightly braver list of your wishes include?",
            "what do you want this morning, before the day tells you what to want?",
        ]),
        PromptTheme(name: "enough", prompts: [
            "if nobody else got to grade your life, what would enough look like?",
            "what in your life would you rather deepen than make bigger?",
            "what are you already doing well enough?",
            "where are you holding yourself to a standard no one could meet?",
            "what would you stop improving if you believed you were allowed to?",
            "what do you already have that you once wished for?",
            "how will you know when you’ve done enough today?",
            "which part of your life is quietly asking to be left as it is?",
            "what would you keep if you had to let half of it go?",
            "what does “more” keep promising you that it never quite delivers?",
            "what could you leave undone today, trusting it can wait?",
            "who are you trying to become that you might already be?",
            "what could you do less of without anything bad happening?",
            "what are you saving for a someday that doesn’t need to wait?",
            "when did you last feel you had plenty?",
            "what would you stop counting if you could?",
            "which ambition feels like yours, and which feels like homework?",
            "what would you do with an hour you didn’t have to earn?",
            "what would change if you accepted who you are, not who you think you ought to be?",
            "what has been quietly sufficient all along?",
            "what is the smallest life you’d still be glad to live?",
            "which “should” could you set down this morning?",
            "what are you trying to hold together that might be allowed to loosen?",
            "what would feel like plenty, rather than finished?",
            "what are you still chasing that you’ve honestly already caught?",
        ]),
        PromptTheme(name: "the body", prompts: [
            "where in your body is today already sitting?",
            "what does your body know about this week that your mind hasn’t admitted?",
            "what is your breath like right now, before you change it?",
            "which part of you is tired in a way sleep won’t fix?",
            "if your current worry had a shape or texture, what would it be?",
            "what would your shoulders say if they got to speak first?",
            "what did your body enjoy yesterday, however small?",
            "when you picture the day ahead, where do you tighten?",
            "which of your choices makes your body feel lighter, and which heavier?",
            "what would it feel like to be kind to your body for one ordinary hour?",
            "where do you feel most at home in your own skin?",
            "what does rest look like for you, as opposed to collapse?",
            "what sensation are you most tempted to ignore today?",
            "how do you know, physically, when something is right for you?",
            "what movement has your body been asking for?",
            "if your body had one request for the week, what would it be?",
            "what does “no” feel like in your body, just before you say yes?",
            "what is the weather inside you right now?",
            "which room, place or kind of light makes your body soften?",
            "what can you hear right now, if you listen for a whole minute?",
            "where have you been treating your body like a machine lately?",
            "what would it mean to take up a little more space today?",
            "what is the sorest part of you asking for this morning?",
            "what does your face do when you’re absorbed in something you love?",
            "what does your body want for breakfast, as opposed to your habits?",
        ]),
        PromptTheme(name: "fear", prompts: [
            "whose disapproval do you find yourself imagining when you picture your ideal life?",
            "what are you not doing because you’re waiting to feel ready?",
            "what’s the worst that could realistically happen, and how would you mend it?",
            "what might an attempt give you, even if it only half works?",
            "what is staying the same quietly costing you?",
            "what are you afraid would happen if you stopped trying so hard?",
            "which of your fears is really trying to protect something you love?",
            "what would you do this week if embarrassment wore off in an hour?",
            "what are you avoiding that would take less than ten minutes?",
            "which worry have you had so long it feels like furniture?",
            "what’s the smallest brave thing available to you today?",
            "where are you choosing comfort, when a little discomfort would serve you better?",
            "what would change if you assumed you might fail and began anyway?",
            "what used to frighten you that no longer does?",
            "what might your worry be asking you to pay attention to?",
            "where are you making yourself small so nobody will be disappointed?",
            "which decision are you postponing in the hope it will make itself?",
            "what will you choose to be bad at, so you can give yourself to something else?",
            "what would you say if you knew your voice wouldn’t shake?",
            "which of your fears did you inherit from someone who raised you?",
            "what are you bracing for that hasn’t happened?",
            "if your fear came to breakfast, what would you offer it?",
            "what would you try if you trusted you’d survive being wrong?",
            "what have you dreamed of doing for years, and what’s kept you from it?",
            "where are you leaning away from something uncomfortable, and what if you leaned in?",
        ]),
        PromptTheme(name: "other people", prompts: [
            "what have you received from someone lately that you haven’t acknowledged?",
            "what have you given this week that nobody asked for?",
            "what trouble have you caused someone without quite meaning to?",
            "who do you become a little more yourself around?",
            "whose day would be slightly lighter if you reached out this morning?",
            "what do you wish someone would ask you?",
            "who are you still trying to impress who isn’t watching anymore?",
            "what conversation have you been rehearsing instead of having?",
            "who taught you something you use every day without thinking of them?",
            "what do you need from the people you love that you haven’t asked for?",
            "when did you last feel truly understood?",
            "where are you giving more than you have, and what’s that about?",
            "which friendship would you like to tend more carefully?",
            "what do you appreciate about someone that you’ve never told them?",
            "who would you like to forgive, even a little, for your own sake?",
            "how do you most like to be loved, in small ways?",
            "when do you feel most generous?",
            "whose opinion of you do you keep checking, even in your head?",
            "who has seen you at your least impressive and stayed?",
            "what does love look like in your home on an ordinary day?",
            "who do you miss, and what exactly do you miss about them?",
            "what would it look like to let someone help you this week?",
            "what small kindness from childhood still warms you?",
            "who would you like to be for the people around you today?",
            "what would you want someone who loves you to know about this season?",
        ]),
        PromptTheme(name: "time", prompts: [
            "which part of your current week do you wish there were more of?",
            "how would you spend your days if you didn’t need to see things finished?",
            "what are you treating as preparation for your real life?",
            "what is worth doing slowly?",
            "where did yesterday’s hours actually go?",
            "what do you keep saying you’ll do when things calm down?",
            "which of your hours feel most like your own?",
            "if this season of your life had a name, what would it be?",
            "looking back from eighty, what would you wish you’d done more of?",
            "what are you rushing through that you’ll one day miss?",
            "what would you stop doing if you remembered how few weeks there are?",
            "what could you let take as long as it takes?",
            "which part of today is already spoken for, and by whom?",
            "when does time disappear for you in the good way?",
            "what have you meant to do for years that would take an afternoon?",
            "what would you do with a day that nobody knew you had?",
            "what could you start now so it’s ready for you in ten years?",
            "what are you waiting for permission to begin?",
            "how do you want this year to feel when you remember it?",
            "what could you do today that your future self would quietly thank you for?",
            "which commitment would you not take on again, knowing what you know now?",
            "what does a well-spent morning look like to you?",
            "what are you holding back on until you feel like you know what you’re doing?",
            "what would you do this month if it were your last one in this place?",
            "which of your days this week will you remember, and why that one?",
        ]),
        PromptTheme(name: "the past", prompts: [
            "what did you want before you learned to justify your choices?",
            "what did you love as a child that you’ve never quite outgrown?",
            "what would the you of ten years ago be surprised by today?",
            "what are you still carrying from a place you’ve already left?",
            "what did you learn about money, rest or love by watching at home?",
            "what memory keeps quietly returning lately, and why now?",
            "when did you last feel completely yourself, and what were you doing?",
            "what does your sweetest memory tell you about what matters to you?",
            "which old story about yourself is ready to be retired?",
            "what did you give up that you’d like to pick back up?",
            "who were you before anybody needed anything from you?",
            "what are you proud of getting through that you rarely mention?",
            "what place from your past do you sometimes wander back to?",
            "what did someone say to you once that you’ve never forgotten?",
            "what turning point did you only recognise much later?",
            "which of your habits is older than you realise?",
            "what have you been meaning to grieve properly?",
            "what did you once believe about adulthood that turned out not to be true?",
            "what felt like the end of the world and wasn’t?",
            "what’s the most important thing you’ve changed your mind about?",
            "what would you like to thank your younger self for?",
            "which part of your past deserves a kinder retelling?",
            "what have you never quite let yourself write about?",
            "what did you do for hours as a kid, and nobody had to make you?",
            "what would you tell yourself at seventeen, and what would seventeen tell you back?",
        ]),
        PromptTheme(name: "attention", prompts: [
            "what did you notice yesterday that almost nobody else would have?",
            "what is the light doing right now, wherever you are?",
            "what astonished you recently, even slightly?",
            "what would you like to pay closer attention to today?",
            "what would you miss terribly if it quietly vanished from your life?",
            "what small surprise lately made a day better?",
            "for what moment yesterday are you most grateful?",
            "which moment yesterday would you rather not relive, and what is it telling you?",
            "what gave you energy yesterday, and what drained it?",
            "where does your attention go when you aren’t steering it?",
            "what are you looking at too often, and what too rarely?",
            "what’s something beautiful you walk past most days?",
            "what would you see if you looked around your home like a visitor?",
            "what, in you, is most asking for attention this morning?",
            "what is one thing you could do today with your whole attention?",
            "which sound, smell or taste is today beginning with?",
            "what do you keep checking, and what are you hoping to find?",
            "what would it mean to be interested rather than busy today?",
            "what small beauty is within arm’s reach right now?",
            "whose face did you really look at yesterday?",
            "what is quietly going right that you haven’t celebrated?",
            "what brings you alive just by being near it?",
            "what would you like to be astonished by this week?",
            "what have you stopped seeing because it’s always there?",
            "what are you learning about yourself from what you notice first?",
        ]),
        PromptTheme(name: "ordinary days", prompts: [
            "what would make an ordinary afternoon easier to love?",
            "what would you like to do with this one wild and precious day?",
            "what would a gentle version of today look like?",
            "what one thing would make today feel like yours?",
            "which ordinary ritual would you miss most if it disappeared?",
            "what would you like to do today for no reason at all?",
            "what could you remove from today to make room for something good?",
            "what does your ideal unremarkable weekday include?",
            "what small pleasure could you plan for this afternoon?",
            "what would make coming home tonight feel good?",
            "what would you like to finish today, and what would you like to leave?",
            "how do you want to feel when you get into bed tonight?",
            "what could you do today worth remembering, though nobody else would?",
            "what part of your routine still feels alive, and what part has gone stale?",
            "what small solo adventure could you take this week, just for delight?",
            "what’s the kindest thing you could put on today’s list?",
            "where could you be a little idle and blessed today?",
            "which chore could become a small ceremony?",
            "what meal, walk or window would make today better?",
            "what do you want to protect about today before it gets busy?",
            "what’s the first good thing that happened this morning?",
            "if today were a page in a novel, what would you want to happen?",
            "what would you like to say yes to today?",
            "what could you kindly decline today, to protect something better?",
            "what does a good day feel like in its first hour?",
        ]),
        PromptTheme(name: "work", prompts: [
            "what would you make if nobody ever saw it, read it or bought it?",
            "what does your work give you besides money?",
            "which part of your work would you keep doing unpaid?",
            "which task are you avoiding, and what is it really asking of you?",
            "if you didn’t have to do it perfectly, what would you try?",
            "what have you been waiting to be good enough to begin?",
            "what are you making right now that you’re secretly proud of?",
            "what do you know how to do that you tend to undervalue?",
            "what kind of tiredness does your work leave you with?",
            "what would you do differently at work if you trusted yourself more?",
            "what is your work asking you to become, and do you want to?",
            "who would you be without the job title?",
            "when did you last lose yourself in something you were making?",
            "what does doing well mean to you, apart from anyone else’s measure?",
            "what skill would you be willing to be patiently bad at for a year?",
            "what would your working day look like if it followed your energy?",
            "what is the most honest thing you could make right now?",
            "what idea keeps returning, however often you dismiss it?",
            "what did you want to be when you grew up, and what was the feeling underneath?",
            "what small piece of work could you finish this morning and feel good about?",
            "where does your work feel like yours, and where like a costume?",
            "what would you keep doing even if you were told you couldn’t?",
            "what are you busy with that doesn’t actually matter to you?",
            "what would you like your work to leave behind?",
            "what are you ready to stop doing, even though you’re good at it?",
        ]),
        PromptTheme(name: "the stories", prompts: [
            "what story are you telling yourself about this week?",
            "what thought has been heaviest lately, and are you sure it’s true?",
            "who would you be this morning without that thought?",
            "what happens in you when you believe you’re falling behind?",
            "what’s the opposite of your harshest thought about yourself, and could it be true too?",
            "what are you sure about someone else that you can’t actually know?",
            "what do you tell yourself you have to do that you’re really choosing?",
            "which part of today is yours to shape, and which part isn’t?",
            "what would you say to a friend who told you the story you tell yourself?",
            "what word do you use about yourself that you’d never use about someone you love?",
            "what are you still arguing with that has already happened?",
            "what advice do you give others that you might need yourself?",
            "which belief about yourself have you never actually checked?",
            "what are you calling a failure that might just be information?",
            "what would change if you assumed the best about the person frustrating you?",
            "what’s the kindest true thing you could say about yourself today?",
            "what would you have to stop believing in order to feel more free?",
            "what do you think you’d lose by being gentler with yourself?",
            "what story about your future are you treating as a fact?",
            "whose voice does your inner critic borrow?",
            "what’s true for you, whatever anyone else decides?",
            "which of your certainties could use some air?",
            "what if the thing you’re resisting is simply how it is right now?",
            "what’s another, equally true version of yesterday’s frustration?",
            "what would you do today if you believed you were doing better than you think?",
        ]),
        PromptTheme(name: "the unclaimed", prompts: [
            "what quality in someone else bothers you in a way that feels familiar?",
            "who do you quietly admire, and what of theirs might already be in you?",
            "what do you envy, and where is the envy pointing?",
            "which part of you has been working hardest lately, and what is it worried about?",
            "what would that hardworking part of you do if it were allowed to rest?",
            "what side of yourself do you tuck away in company?",
            "what are you secretly good at?",
            "which of your moods do you judge most, and what might it be protecting?",
            "how do you feel toward the part of you that keeps putting things off?",
            "what do you tend to do when you’re hurt, instead of saying so?",
            "what were you once told was “too much” about you?",
            "what would you let yourself be if you weren’t worried about seeming selfish?",
            "which compliment do you always wave away?",
            "what part of you rarely gets a say in your decisions?",
            "what would the quietest part of you say if it had the floor this morning?",
            "what gift do you downplay so others won’t feel uncomfortable?",
            "what anger have you been politely ignoring?",
            "what would you do differently if you stopped needing to be the easy one?",
            "which of your roles fits least comfortably right now?",
            "what are you a little ashamed of wanting, and is it really so bad?",
            "when do you perform being fine?",
            "what do you admire in yourself that you rarely say aloud?",
            "what does your stubbornness protect?",
            "what would you forgive in a friend but not yet in yourself?",
            "which feeling do you tidy away fastest?",
        ]),
    ]

    /// Flattened, in theme order. `PromptDeck` shuffles indices into this.
    static let all: [Prompt] = themes.flatMap { theme in
        theme.prompts.map { Prompt(text: $0, theme: theme.name) }
    }
}
